component:
  source_name: name
  source_part_number: part_number
  source_weight: weight_g
material:
  source_name: name
  source_material_number: material_number
  source_classification: classification
substance:
  source_name: name
  source_cas: cas_number
  source_percentage: percentage
